package com.lanou.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AuthUser {
    
    private String AUTH_USER_ID;

    
    private String USERNAME;

    
    private String PASSWORD;

    
    private BigDecimal SALARY;

    
    private Date BIRTHDAY;

    
    private String GENDER;

    
    private String STATION;

    
    private String TELEPHONE;

    
    private String REMARK;

    
    private String DEGREE;

    
    private String MANAGER_ID;

    
    private String CREATE_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CREATE_DEPT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.AUTH_USER_ID
     *
     * @return the value of AUTH_USER_P.AUTH_USER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getAUTH_USER_ID() {
        return AUTH_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.AUTH_USER_ID
     *
     * @param AUTH_USER_ID the value for AUTH_USER_P.AUTH_USER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setAUTH_USER_ID(String AUTH_USER_ID) {
        this.AUTH_USER_ID = AUTH_USER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.USERNAME
     *
     * @return the value of AUTH_USER_P.USERNAME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getUSERNAME() {
        return USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.USERNAME
     *
     * @param USERNAME the value for AUTH_USER_P.USERNAME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setUSERNAME(String USERNAME) {
        this.USERNAME = USERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.PASSWORD
     *
     * @return the value of AUTH_USER_P.PASSWORD
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getPASSWORD() {
        return PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.PASSWORD
     *
     * @param PASSWORD the value for AUTH_USER_P.PASSWORD
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setPASSWORD(String PASSWORD) {
        this.PASSWORD = PASSWORD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.SALARY
     *
     * @return the value of AUTH_USER_P.SALARY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public BigDecimal getSALARY() {
        return SALARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.SALARY
     *
     * @param SALARY the value for AUTH_USER_P.SALARY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSALARY(BigDecimal SALARY) {
        this.SALARY = SALARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.BIRTHDAY
     *
     * @return the value of AUTH_USER_P.BIRTHDAY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getBIRTHDAY() {
        return BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.BIRTHDAY
     *
     * @param BIRTHDAY the value for AUTH_USER_P.BIRTHDAY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setBIRTHDAY(Date BIRTHDAY) {
        this.BIRTHDAY = BIRTHDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.GENDER
     *
     * @return the value of AUTH_USER_P.GENDER
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getGENDER() {
        return GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.GENDER
     *
     * @param GENDER the value for AUTH_USER_P.GENDER
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setGENDER(String GENDER) {
        this.GENDER = GENDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.STATION
     *
     * @return the value of AUTH_USER_P.STATION
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getSTATION() {
        return STATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.STATION
     *
     * @param STATION the value for AUTH_USER_P.STATION
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSTATION(String STATION) {
        this.STATION = STATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.TELEPHONE
     *
     * @return the value of AUTH_USER_P.TELEPHONE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getTELEPHONE() {
        return TELEPHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.TELEPHONE
     *
     * @param TELEPHONE the value for AUTH_USER_P.TELEPHONE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setTELEPHONE(String TELEPHONE) {
        this.TELEPHONE = TELEPHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.REMARK
     *
     * @return the value of AUTH_USER_P.REMARK
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.REMARK
     *
     * @param REMARK the value for AUTH_USER_P.REMARK
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.DEGREE
     *
     * @return the value of AUTH_USER_P.DEGREE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getDEGREE() {
        return DEGREE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.DEGREE
     *
     * @param DEGREE the value for AUTH_USER_P.DEGREE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setDEGREE(String DEGREE) {
        this.DEGREE = DEGREE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.MANAGER_ID
     *
     * @return the value of AUTH_USER_P.MANAGER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getMANAGER_ID() {
        return MANAGER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.MANAGER_ID
     *
     * @param MANAGER_ID the value for AUTH_USER_P.MANAGER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setMANAGER_ID(String MANAGER_ID) {
        this.MANAGER_ID = MANAGER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_BY
     *
     * @return the value of AUTH_USER_P.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_BY
     *
     * @param CREATE_BY the value for AUTH_USER_P.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_DEPT
     *
     * @return the value of AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for AUTH_USER_P.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTH_USER_P.CREATE_TIME
     *
     * @return the value of AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTH_USER_P.CREATE_TIME
     *
     * @param CREATE_TIME the value for AUTH_USER_P.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}