package com.lanou.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Contractproducthisc implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CONTRACT_PRODUCT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CONTRACT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_IMAGE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_DESC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short CNUMBER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short OUT_NUMBER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String LOADING_RATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short BOX_NUM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PACKING_UNIT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private BigDecimal PRICE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private BigDecimal AMOUNT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short FINISHED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String EXTS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short ORDER_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCONTRACT_PRODUCT_ID() {
        return CONTRACT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @param CONTRACT_PRODUCT_ID the value for CONTRACT_PRODUCT_HIS_C.CONTRACT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCONTRACT_PRODUCT_ID(String CONTRACT_PRODUCT_ID) {
        this.CONTRACT_PRODUCT_ID = CONTRACT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCONTRACT_ID() {
        return CONTRACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @param CONTRACT_ID the value for CONTRACT_PRODUCT_HIS_C.CONTRACT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCONTRACT_ID(String CONTRACT_ID) {
        this.CONTRACT_ID = CONTRACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_ID() {
        return FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @param FACTORY_ID the value for CONTRACT_PRODUCT_HIS_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_ID(String FACTORY_ID) {
        this.FACTORY_ID = FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_NAME() {
        return FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @param FACTORY_NAME the value for CONTRACT_PRODUCT_HIS_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_NAME(String FACTORY_NAME) {
        this.FACTORY_NAME = FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_NO() {
        return PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @param PRODUCT_NO the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_NO(String PRODUCT_NO) {
        this.PRODUCT_NO = PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_IMAGE() {
        return PRODUCT_IMAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @param PRODUCT_IMAGE the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_IMAGE(String PRODUCT_IMAGE) {
        this.PRODUCT_IMAGE = PRODUCT_IMAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_DESC() {
        return PRODUCT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @param PRODUCT_DESC the value for CONTRACT_PRODUCT_HIS_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_DESC(String PRODUCT_DESC) {
        this.PRODUCT_DESC = PRODUCT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getCNUMBER() {
        return CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @param CNUMBER the value for CONTRACT_PRODUCT_HIS_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCNUMBER(Short CNUMBER) {
        this.CNUMBER = CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getOUT_NUMBER() {
        return OUT_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @param OUT_NUMBER the value for CONTRACT_PRODUCT_HIS_C.OUT_NUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setOUT_NUMBER(Short OUT_NUMBER) {
        this.OUT_NUMBER = OUT_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getLOADING_RATE() {
        return LOADING_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @param LOADING_RATE the value for CONTRACT_PRODUCT_HIS_C.LOADING_RATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setLOADING_RATE(String LOADING_RATE) {
        this.LOADING_RATE = LOADING_RATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getBOX_NUM() {
        return BOX_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @param BOX_NUM the value for CONTRACT_PRODUCT_HIS_C.BOX_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setBOX_NUM(Short BOX_NUM) {
        this.BOX_NUM = BOX_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPACKING_UNIT() {
        return PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @param PACKING_UNIT the value for CONTRACT_PRODUCT_HIS_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPACKING_UNIT(String PACKING_UNIT) {
        this.PACKING_UNIT = PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getPRICE() {
        return PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @param PRICE the value for CONTRACT_PRODUCT_HIS_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRICE(BigDecimal PRICE) {
        this.PRICE = PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @param AMOUNT the value for CONTRACT_PRODUCT_HIS_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getFINISHED() {
        return FINISHED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @param FINISHED the value for CONTRACT_PRODUCT_HIS_C.FINISHED
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFINISHED(Short FINISHED) {
        this.FINISHED = FINISHED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getEXTS() {
        return EXTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @param EXTS the value for CONTRACT_PRODUCT_HIS_C.EXTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEXTS(String EXTS) {
        this.EXTS = EXTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @return the value of CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @param ORDER_NO the value for CONTRACT_PRODUCT_HIS_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setORDER_NO(Short ORDER_NO) {
        this.ORDER_NO = ORDER_NO;
    }
}