package com.lanou.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Contractc implements Serializable{
    private String CONTRACT_ID;

    private String OFFEROR;

    private String CONTRACT_NO;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date SIGNING_DATE;

    private String INPUT_BY;

    private String CHECK_BY;

    private String INSPECTOR;

    private BigDecimal TOTAL_AMOUNT;

    private Short IMPORT_NUM;

    private String CREQUEST;

    private String CUSTOM_NAME;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date DELIVERY_PERIOD;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date SHIP_TIME;

    private String TRADE_TERMS;

    private String REMARK;

    private String PRINT_STYLE;

    private Short OLD_STATE;

    private Short STATE;

    private Short OUT_STATE;

    private String CREATE_BY;

    private String CREATE_DEPT;
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date CREATE_TIME;

    public String getCONTRACT_ID() {
        return CONTRACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CONTRACT_ID
     *
     * @param CONTRACT_ID the value for CONTRACT_C.CONTRACT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCONTRACT_ID(String CONTRACT_ID) {
        this.CONTRACT_ID = CONTRACT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.OFFEROR
     *
     * @return the value of CONTRACT_C.OFFEROR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getOFFEROR() {
        return OFFEROR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.OFFEROR
     *
     * @param OFFEROR the value for CONTRACT_C.OFFEROR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setOFFEROR(String OFFEROR) {
        this.OFFEROR = OFFEROR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CONTRACT_NO
     *
     * @return the value of CONTRACT_C.CONTRACT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCONTRACT_NO() {
        return CONTRACT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CONTRACT_NO
     *
     * @param CONTRACT_NO the value for CONTRACT_C.CONTRACT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCONTRACT_NO(String CONTRACT_NO) {
        this.CONTRACT_NO = CONTRACT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.SIGNING_DATE
     *
     * @return the value of CONTRACT_C.SIGNING_DATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Date getSIGNING_DATE() {
        return SIGNING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.SIGNING_DATE
     *
     * @param SIGNING_DATE the value for CONTRACT_C.SIGNING_DATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSIGNING_DATE(Date SIGNING_DATE) {
        this.SIGNING_DATE = SIGNING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.INPUT_BY
     *
     * @return the value of CONTRACT_C.INPUT_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getINPUT_BY() {
        return INPUT_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.INPUT_BY
     *
     * @param INPUT_BY the value for CONTRACT_C.INPUT_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setINPUT_BY(String INPUT_BY) {
        this.INPUT_BY = INPUT_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CHECK_BY
     *
     * @return the value of CONTRACT_C.CHECK_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCHECK_BY() {
        return CHECK_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CHECK_BY
     *
     * @param CHECK_BY the value for CONTRACT_C.CHECK_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCHECK_BY(String CHECK_BY) {
        this.CHECK_BY = CHECK_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.INSPECTOR
     *
     * @return the value of CONTRACT_C.INSPECTOR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getINSPECTOR() {
        return INSPECTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.INSPECTOR
     *
     * @param INSPECTOR the value for CONTRACT_C.INSPECTOR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setINSPECTOR(String INSPECTOR) {
        this.INSPECTOR = INSPECTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.TOTAL_AMOUNT
     *
     * @return the value of CONTRACT_C.TOTAL_AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getTOTAL_AMOUNT() {
        return TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.TOTAL_AMOUNT
     *
     * @param TOTAL_AMOUNT the value for CONTRACT_C.TOTAL_AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setTOTAL_AMOUNT(BigDecimal TOTAL_AMOUNT) {
        this.TOTAL_AMOUNT = TOTAL_AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.IMPORT_NUM
     *
     * @return the value of CONTRACT_C.IMPORT_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getIMPORT_NUM() {
        return IMPORT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.IMPORT_NUM
     *
     * @param IMPORT_NUM the value for CONTRACT_C.IMPORT_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setIMPORT_NUM(Short IMPORT_NUM) {
        this.IMPORT_NUM = IMPORT_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CREQUEST
     *
     * @return the value of CONTRACT_C.CREQUEST
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCREQUEST() {
        return CREQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CREQUEST
     *
     * @param CREQUEST the value for CONTRACT_C.CREQUEST
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREQUEST(String CREQUEST) {
        this.CREQUEST = CREQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CUSTOM_NAME
     *
     * @return the value of CONTRACT_C.CUSTOM_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCUSTOM_NAME() {
        return CUSTOM_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CUSTOM_NAME
     *
     * @param CUSTOM_NAME the value for CONTRACT_C.CUSTOM_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCUSTOM_NAME(String CUSTOM_NAME) {
        this.CUSTOM_NAME = CUSTOM_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.DELIVERY_PERIOD
     *
     * @return the value of CONTRACT_C.DELIVERY_PERIOD
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Date getDELIVERY_PERIOD() {
        return DELIVERY_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.DELIVERY_PERIOD
     *
     * @param DELIVERY_PERIOD the value for CONTRACT_C.DELIVERY_PERIOD
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setDELIVERY_PERIOD(Date DELIVERY_PERIOD) {
        this.DELIVERY_PERIOD = DELIVERY_PERIOD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.SHIP_TIME
     *
     * @return the value of CONTRACT_C.SHIP_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Date getSHIP_TIME() {
        return SHIP_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.SHIP_TIME
     *
     * @param SHIP_TIME the value for CONTRACT_C.SHIP_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSHIP_TIME(Date SHIP_TIME) {
        this.SHIP_TIME = SHIP_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.TRADE_TERMS
     *
     * @return the value of CONTRACT_C.TRADE_TERMS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getTRADE_TERMS() {
        return TRADE_TERMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.TRADE_TERMS
     *
     * @param TRADE_TERMS the value for CONTRACT_C.TRADE_TERMS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setTRADE_TERMS(String TRADE_TERMS) {
        this.TRADE_TERMS = TRADE_TERMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.REMARK
     *
     * @return the value of CONTRACT_C.REMARK
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getREMARK() {
        return REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.REMARK
     *
     * @param REMARK the value for CONTRACT_C.REMARK
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setREMARK(String REMARK) {
        this.REMARK = REMARK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.PRINT_STYLE
     *
     * @return the value of CONTRACT_C.PRINT_STYLE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRINT_STYLE() {
        return PRINT_STYLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.PRINT_STYLE
     *
     * @param PRINT_STYLE the value for CONTRACT_C.PRINT_STYLE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRINT_STYLE(String PRINT_STYLE) {
        this.PRINT_STYLE = PRINT_STYLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.OLD_STATE
     *
     * @return the value of CONTRACT_C.OLD_STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getOLD_STATE() {
        return OLD_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.OLD_STATE
     *
     * @param OLD_STATE the value for CONTRACT_C.OLD_STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setOLD_STATE(Short OLD_STATE) {
        this.OLD_STATE = OLD_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.STATE
     *
     * @return the value of CONTRACT_C.STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.STATE
     *
     * @param STATE the value for CONTRACT_C.STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSTATE(Short STATE) {
        this.STATE = STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.OUT_STATE
     *
     * @return the value of CONTRACT_C.OUT_STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getOUT_STATE() {
        return OUT_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.OUT_STATE
     *
     * @param OUT_STATE the value for CONTRACT_C.OUT_STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setOUT_STATE(Short OUT_STATE) {
        this.OUT_STATE = OUT_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CREATE_BY
     *
     * @return the value of CONTRACT_C.CREATE_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CREATE_BY
     *
     * @param CREATE_BY the value for CONTRACT_C.CREATE_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CREATE_DEPT
     *
     * @return the value of CONTRACT_C.CREATE_DEPT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for CONTRACT_C.CREATE_DEPT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONTRACT_C.CREATE_TIME
     *
     * @return the value of CONTRACT_C.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONTRACT_C.CREATE_TIME
     *
     * @param CREATE_TIME the value for CONTRACT_C.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}