package com.lanou.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Exportproductc implements Serializable{
    private String EXPORT_PRODUCT_ID;

    private String EXPORT_ID;

    private String FACTORY_ID;

    private String FACTORY_NAME;

    private String PRODUCT_NO;

    private String PACKING_UNIT;

    private Short CNUMBER;

    private Short BOX_NUM;

    private BigDecimal GROSS_WEIGHT;

    private BigDecimal NET_WEIGHT;

    private BigDecimal SIZE_LENGTH;

    private BigDecimal SIZE_WIDTH;

    private BigDecimal SIZE_HEIGHT;

    private BigDecimal EX_PRICE;

    private BigDecimal PRICE;

    private BigDecimal TAX;

    private Short ORDER_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @return the value of EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getEXPORT_PRODUCT_ID() {
        return EXPORT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @param EXPORT_PRODUCT_ID the value for EXPORT_PRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEXPORT_PRODUCT_ID(String EXPORT_PRODUCT_ID) {
        this.EXPORT_PRODUCT_ID = EXPORT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @return the value of EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getEXPORT_ID() {
        return EXPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @param EXPORT_ID the value for EXPORT_PRODUCT_C.EXPORT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEXPORT_ID(String EXPORT_ID) {
        this.EXPORT_ID = EXPORT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @return the value of EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_ID() {
        return FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @param FACTORY_ID the value for EXPORT_PRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_ID(String FACTORY_ID) {
        this.FACTORY_ID = FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @return the value of EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_NAME() {
        return FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @param FACTORY_NAME the value for EXPORT_PRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_NAME(String FACTORY_NAME) {
        this.FACTORY_NAME = FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @return the value of EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_NO() {
        return PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @param PRODUCT_NO the value for EXPORT_PRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_NO(String PRODUCT_NO) {
        this.PRODUCT_NO = PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @return the value of EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPACKING_UNIT() {
        return PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @param PACKING_UNIT the value for EXPORT_PRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPACKING_UNIT(String PACKING_UNIT) {
        this.PACKING_UNIT = PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.CNUMBER
     *
     * @return the value of EXPORT_PRODUCT_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getCNUMBER() {
        return CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.CNUMBER
     *
     * @param CNUMBER the value for EXPORT_PRODUCT_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCNUMBER(Short CNUMBER) {
        this.CNUMBER = CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.BOX_NUM
     *
     * @return the value of EXPORT_PRODUCT_C.BOX_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getBOX_NUM() {
        return BOX_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.BOX_NUM
     *
     * @param BOX_NUM the value for EXPORT_PRODUCT_C.BOX_NUM
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setBOX_NUM(Short BOX_NUM) {
        this.BOX_NUM = BOX_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getGROSS_WEIGHT() {
        return GROSS_WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @param GROSS_WEIGHT the value for EXPORT_PRODUCT_C.GROSS_WEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setGROSS_WEIGHT(BigDecimal GROSS_WEIGHT) {
        this.GROSS_WEIGHT = GROSS_WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getNET_WEIGHT() {
        return NET_WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @param NET_WEIGHT the value for EXPORT_PRODUCT_C.NET_WEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setNET_WEIGHT(BigDecimal NET_WEIGHT) {
        this.NET_WEIGHT = NET_WEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getSIZE_LENGTH() {
        return SIZE_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @param SIZE_LENGTH the value for EXPORT_PRODUCT_C.SIZE_LENGTH
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSIZE_LENGTH(BigDecimal SIZE_LENGTH) {
        this.SIZE_LENGTH = SIZE_LENGTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getSIZE_WIDTH() {
        return SIZE_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @param SIZE_WIDTH the value for EXPORT_PRODUCT_C.SIZE_WIDTH
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSIZE_WIDTH(BigDecimal SIZE_WIDTH) {
        this.SIZE_WIDTH = SIZE_WIDTH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @return the value of EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getSIZE_HEIGHT() {
        return SIZE_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @param SIZE_HEIGHT the value for EXPORT_PRODUCT_C.SIZE_HEIGHT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSIZE_HEIGHT(BigDecimal SIZE_HEIGHT) {
        this.SIZE_HEIGHT = SIZE_HEIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.EX_PRICE
     *
     * @return the value of EXPORT_PRODUCT_C.EX_PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getEX_PRICE() {
        return EX_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.EX_PRICE
     *
     * @param EX_PRICE the value for EXPORT_PRODUCT_C.EX_PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEX_PRICE(BigDecimal EX_PRICE) {
        this.EX_PRICE = EX_PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.PRICE
     *
     * @return the value of EXPORT_PRODUCT_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getPRICE() {
        return PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.PRICE
     *
     * @param PRICE the value for EXPORT_PRODUCT_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRICE(BigDecimal PRICE) {
        this.PRICE = PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.TAX
     *
     * @return the value of EXPORT_PRODUCT_C.TAX
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getTAX() {
        return TAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.TAX
     *
     * @param TAX the value for EXPORT_PRODUCT_C.TAX
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setTAX(BigDecimal TAX) {
        this.TAX = TAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORT_PRODUCT_C.ORDER_NO
     *
     * @return the value of EXPORT_PRODUCT_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORT_PRODUCT_C.ORDER_NO
     *
     * @param ORDER_NO the value for EXPORT_PRODUCT_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setORDER_NO(Short ORDER_NO) {
        this.ORDER_NO = ORDER_NO;
    }
}