package com.lanou.entity;

import java.io.Serializable;
import java.math.BigDecimal;

public class Exteproductc implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.EXT_EPRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String EXT_EPRODUCT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String EXPORT_PRODUCT_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.CTYPE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short CTYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_IMAGE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_DESC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short CNUMBER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PACKING_UNIT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private BigDecimal PRICE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private BigDecimal AMOUNT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PRODUCT_REQUEST;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXT_EPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short ORDER_NO;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.EXT_EPRODUCT_ID
     *
     * @return the value of EXT_EPRODUCT_C.EXT_EPRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getEXT_EPRODUCT_ID() {
        return EXT_EPRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.EXT_EPRODUCT_ID
     *
     * @param EXT_EPRODUCT_ID the value for EXT_EPRODUCT_C.EXT_EPRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEXT_EPRODUCT_ID(String EXT_EPRODUCT_ID) {
        this.EXT_EPRODUCT_ID = EXT_EPRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @return the value of EXT_EPRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getEXPORT_PRODUCT_ID() {
        return EXPORT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @param EXPORT_PRODUCT_ID the value for EXT_EPRODUCT_C.EXPORT_PRODUCT_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setEXPORT_PRODUCT_ID(String EXPORT_PRODUCT_ID) {
        this.EXPORT_PRODUCT_ID = EXPORT_PRODUCT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.FACTORY_ID
     *
     * @return the value of EXT_EPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_ID() {
        return FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.FACTORY_ID
     *
     * @param FACTORY_ID the value for EXT_EPRODUCT_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_ID(String FACTORY_ID) {
        this.FACTORY_ID = FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.FACTORY_NAME
     *
     * @return the value of EXT_EPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_NAME() {
        return FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.FACTORY_NAME
     *
     * @param FACTORY_NAME the value for EXT_EPRODUCT_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_NAME(String FACTORY_NAME) {
        this.FACTORY_NAME = FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.CTYPE
     *
     * @return the value of EXT_EPRODUCT_C.CTYPE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getCTYPE() {
        return CTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.CTYPE
     *
     * @param CTYPE the value for EXT_EPRODUCT_C.CTYPE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCTYPE(Short CTYPE) {
        this.CTYPE = CTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PRODUCT_NO
     *
     * @return the value of EXT_EPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_NO() {
        return PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PRODUCT_NO
     *
     * @param PRODUCT_NO the value for EXT_EPRODUCT_C.PRODUCT_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_NO(String PRODUCT_NO) {
        this.PRODUCT_NO = PRODUCT_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PRODUCT_IMAGE
     *
     * @return the value of EXT_EPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_IMAGE() {
        return PRODUCT_IMAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PRODUCT_IMAGE
     *
     * @param PRODUCT_IMAGE the value for EXT_EPRODUCT_C.PRODUCT_IMAGE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_IMAGE(String PRODUCT_IMAGE) {
        this.PRODUCT_IMAGE = PRODUCT_IMAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PRODUCT_DESC
     *
     * @return the value of EXT_EPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_DESC() {
        return PRODUCT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PRODUCT_DESC
     *
     * @param PRODUCT_DESC the value for EXT_EPRODUCT_C.PRODUCT_DESC
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_DESC(String PRODUCT_DESC) {
        this.PRODUCT_DESC = PRODUCT_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.CNUMBER
     *
     * @return the value of EXT_EPRODUCT_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getCNUMBER() {
        return CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.CNUMBER
     *
     * @param CNUMBER the value for EXT_EPRODUCT_C.CNUMBER
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCNUMBER(Short CNUMBER) {
        this.CNUMBER = CNUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PACKING_UNIT
     *
     * @return the value of EXT_EPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPACKING_UNIT() {
        return PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PACKING_UNIT
     *
     * @param PACKING_UNIT the value for EXT_EPRODUCT_C.PACKING_UNIT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPACKING_UNIT(String PACKING_UNIT) {
        this.PACKING_UNIT = PACKING_UNIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PRICE
     *
     * @return the value of EXT_EPRODUCT_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getPRICE() {
        return PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PRICE
     *
     * @param PRICE the value for EXT_EPRODUCT_C.PRICE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRICE(BigDecimal PRICE) {
        this.PRICE = PRICE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.AMOUNT
     *
     * @return the value of EXT_EPRODUCT_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public BigDecimal getAMOUNT() {
        return AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.AMOUNT
     *
     * @param AMOUNT the value for EXT_EPRODUCT_C.AMOUNT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setAMOUNT(BigDecimal AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.PRODUCT_REQUEST
     *
     * @return the value of EXT_EPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPRODUCT_REQUEST() {
        return PRODUCT_REQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.PRODUCT_REQUEST
     *
     * @param PRODUCT_REQUEST the value for EXT_EPRODUCT_C.PRODUCT_REQUEST
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPRODUCT_REQUEST(String PRODUCT_REQUEST) {
        this.PRODUCT_REQUEST = PRODUCT_REQUEST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXT_EPRODUCT_C.ORDER_NO
     *
     * @return the value of EXT_EPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXT_EPRODUCT_C.ORDER_NO
     *
     * @param ORDER_NO the value for EXT_EPRODUCT_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setORDER_NO(Short ORDER_NO) {
        this.ORDER_NO = ORDER_NO;
    }
}