package com.lanou.entity;

import java.io.Serializable;
import java.util.Date;

public class Factoryc implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FULL_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FULL_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FACTORY_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CONTACTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CONTACTS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.PHONE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String PHONE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.MOBILE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String MOBILE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.FAX
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String FAX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CNOTE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CNOTE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.INSPECTOR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String INSPECTOR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Short ORDER_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CREATE_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private String CREATE_DEPT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FACTORY_ID
     *
     * @return the value of FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_ID() {
        return FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FACTORY_ID
     *
     * @param FACTORY_ID the value for FACTORY_C.FACTORY_ID
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_ID(String FACTORY_ID) {
        this.FACTORY_ID = FACTORY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FULL_NAME
     *
     * @return the value of FACTORY_C.FULL_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFULL_NAME() {
        return FULL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FULL_NAME
     *
     * @param FULL_NAME the value for FACTORY_C.FULL_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFULL_NAME(String FULL_NAME) {
        this.FULL_NAME = FULL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FACTORY_NAME
     *
     * @return the value of FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFACTORY_NAME() {
        return FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FACTORY_NAME
     *
     * @param FACTORY_NAME the value for FACTORY_C.FACTORY_NAME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFACTORY_NAME(String FACTORY_NAME) {
        this.FACTORY_NAME = FACTORY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CONTACTS
     *
     * @return the value of FACTORY_C.CONTACTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCONTACTS() {
        return CONTACTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CONTACTS
     *
     * @param CONTACTS the value for FACTORY_C.CONTACTS
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCONTACTS(String CONTACTS) {
        this.CONTACTS = CONTACTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.PHONE
     *
     * @return the value of FACTORY_C.PHONE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getPHONE() {
        return PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.PHONE
     *
     * @param PHONE the value for FACTORY_C.PHONE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setPHONE(String PHONE) {
        this.PHONE = PHONE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.MOBILE
     *
     * @return the value of FACTORY_C.MOBILE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getMOBILE() {
        return MOBILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.MOBILE
     *
     * @param MOBILE the value for FACTORY_C.MOBILE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setMOBILE(String MOBILE) {
        this.MOBILE = MOBILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.FAX
     *
     * @return the value of FACTORY_C.FAX
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getFAX() {
        return FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.FAX
     *
     * @param FAX the value for FACTORY_C.FAX
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setFAX(String FAX) {
        this.FAX = FAX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CNOTE
     *
     * @return the value of FACTORY_C.CNOTE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCNOTE() {
        return CNOTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CNOTE
     *
     * @param CNOTE the value for FACTORY_C.CNOTE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCNOTE(String CNOTE) {
        this.CNOTE = CNOTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.INSPECTOR
     *
     * @return the value of FACTORY_C.INSPECTOR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getINSPECTOR() {
        return INSPECTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.INSPECTOR
     *
     * @param INSPECTOR the value for FACTORY_C.INSPECTOR
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setINSPECTOR(String INSPECTOR) {
        this.INSPECTOR = INSPECTOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.ORDER_NO
     *
     * @return the value of FACTORY_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Short getORDER_NO() {
        return ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.ORDER_NO
     *
     * @param ORDER_NO the value for FACTORY_C.ORDER_NO
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setORDER_NO(Short ORDER_NO) {
        this.ORDER_NO = ORDER_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.STATE
     *
     * @return the value of FACTORY_C.STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.STATE
     *
     * @param STATE the value for FACTORY_C.STATE
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_BY
     *
     * @return the value of FACTORY_C.CREATE_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_BY
     *
     * @param CREATE_BY the value for FACTORY_C.CREATE_BY
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_DEPT
     *
     * @return the value of FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for FACTORY_C.CREATE_DEPT
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FACTORY_C.CREATE_TIME
     *
     * @return the value of FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FACTORY_C.CREATE_TIME
     *
     * @param CREATE_TIME the value for FACTORY_C.CREATE_TIME
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}