package com.lanou.entity;

import java.util.Date;

public class Finance {
   
    private String FINANCE_ID;

    
    private Date INPUT_DATE;

    
    private String INPUT_BY;

    
    private Short STATE;

    
    private String CREATE_BY;

    
    private String CREATE_DEPT;

    
    private Date CREATE_TIME;

   
    public String getFINANCE_ID() {
        return FINANCE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.FINANCE_ID
     *
     * @param FINANCE_ID the value for FINANCE_C.FINANCE_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setFINANCE_ID(String FINANCE_ID) {
        this.FINANCE_ID = FINANCE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.INPUT_DATE
     *
     * @return the value of FINANCE_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getINPUT_DATE() {
        return INPUT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.INPUT_DATE
     *
     * @param INPUT_DATE the value for FINANCE_C.INPUT_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setINPUT_DATE(Date INPUT_DATE) {
        this.INPUT_DATE = INPUT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.INPUT_BY
     *
     * @return the value of FINANCE_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getINPUT_BY() {
        return INPUT_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.INPUT_BY
     *
     * @param INPUT_BY the value for FINANCE_C.INPUT_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setINPUT_BY(String INPUT_BY) {
        this.INPUT_BY = INPUT_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.STATE
     *
     * @return the value of FINANCE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Short getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.STATE
     *
     * @param STATE the value for FINANCE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSTATE(Short STATE) {
        this.STATE = STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_BY
     *
     * @return the value of FINANCE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_BY
     *
     * @param CREATE_BY the value for FINANCE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_DEPT
     *
     * @return the value of FINANCE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for FINANCE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FINANCE_C.CREATE_TIME
     *
     * @return the value of FINANCE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FINANCE_C.CREATE_TIME
     *
     * @param CREATE_TIME the value for FINANCE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}