package com.lanou.entity;

import java.util.Date;

public class Invoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.INVOICE_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String INVOICE_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.SC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String SC_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.BL_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String BL_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String TRADE_TERMS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Short STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CREATE_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CREATE_DEPT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INVOICE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.INVOICE_ID
     *
     * @return the value of INVOICE_C.INVOICE_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getINVOICE_ID() {
        return INVOICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.INVOICE_ID
     *
     * @param INVOICE_ID the value for INVOICE_C.INVOICE_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setINVOICE_ID(String INVOICE_ID) {
        this.INVOICE_ID = INVOICE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.SC_NO
     *
     * @return the value of INVOICE_C.SC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getSC_NO() {
        return SC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.SC_NO
     *
     * @param SC_NO the value for INVOICE_C.SC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSC_NO(String SC_NO) {
        this.SC_NO = SC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.BL_NO
     *
     * @return the value of INVOICE_C.BL_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getBL_NO() {
        return BL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.BL_NO
     *
     * @param BL_NO the value for INVOICE_C.BL_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setBL_NO(String BL_NO) {
        this.BL_NO = BL_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.TRADE_TERMS
     *
     * @return the value of INVOICE_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getTRADE_TERMS() {
        return TRADE_TERMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.TRADE_TERMS
     *
     * @param TRADE_TERMS the value for INVOICE_C.TRADE_TERMS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setTRADE_TERMS(String TRADE_TERMS) {
        this.TRADE_TERMS = TRADE_TERMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.STATE
     *
     * @return the value of INVOICE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Short getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.STATE
     *
     * @param STATE the value for INVOICE_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSTATE(Short STATE) {
        this.STATE = STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.CREATE_BY
     *
     * @return the value of INVOICE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.CREATE_BY
     *
     * @param CREATE_BY the value for INVOICE_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.CREATE_DEPT
     *
     * @return the value of INVOICE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for INVOICE_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INVOICE_C.CREATE_TIME
     *
     * @return the value of INVOICE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INVOICE_C.CREATE_TIME
     *
     * @param CREATE_TIME the value for INVOICE_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}