package com.lanou.entity;

import java.util.Date;

public class LoginLogp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String LOGIN_LOG_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String LOGIN_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String IP_ADDRESS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date LOGIN_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @return the value of LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getLOGIN_LOG_ID() {
        return LOGIN_LOG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @param LOGIN_LOG_ID the value for LOGIN_LOG_P.LOGIN_LOG_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLOGIN_LOG_ID(String LOGIN_LOG_ID) {
        this.LOGIN_LOG_ID = LOGIN_LOG_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @return the value of LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getLOGIN_NAME() {
        return LOGIN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_NAME
     *
     * @param LOGIN_NAME the value for LOGIN_LOG_P.LOGIN_NAME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLOGIN_NAME(String LOGIN_NAME) {
        this.LOGIN_NAME = LOGIN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @return the value of LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getIP_ADDRESS() {
        return IP_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.IP_ADDRESS
     *
     * @param IP_ADDRESS the value for LOGIN_LOG_P.IP_ADDRESS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setIP_ADDRESS(String IP_ADDRESS) {
        this.IP_ADDRESS = IP_ADDRESS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @return the value of LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getLOGIN_TIME() {
        return LOGIN_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_LOG_P.LOGIN_TIME
     *
     * @param LOGIN_TIME the value for LOGIN_LOG_P.LOGIN_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLOGIN_TIME(Date LOGIN_TIME) {
        this.LOGIN_TIME = LOGIN_TIME;
    }
}