package com.lanou.entity;

import java.util.Date;

public class ShippinGorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.SHIPPING_ORDER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String SHIPPING_ORDER_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.ORDER_TYPE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String ORDER_TYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.SHIPPER
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String SHIPPER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CONSIGNEE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.NOTIFY_PARTY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String NOTIFY_PARTY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.LC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String LC_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.PORT_OF_LOADING
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String PORT_OF_LOADING;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.PORT_OF_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String PORT_OF_TRANS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.PORT_OF_DISCHARGE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String PORT_OF_DISCHARGE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.LOADING_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date LOADING_DATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.LIMIT_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date LIMIT_DATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.IS_BATCH
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String IS_BATCH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.IS_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String IS_TRANS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.COPY_NUM
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String COPY_NUM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CNOTE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.SPECIAL_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String SPECIAL_CONDITION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.FREIGHT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String FREIGHT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CHECK_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Short STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CREATE_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private String CREATE_DEPT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SHIPPING_ORDER_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    private Date CREATE_TIME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.SHIPPING_ORDER_ID
     *
     * @return the value of SHIPPING_ORDER_C.SHIPPING_ORDER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getSHIPPING_ORDER_ID() {
        return SHIPPING_ORDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.SHIPPING_ORDER_ID
     *
     * @param SHIPPING_ORDER_ID the value for SHIPPING_ORDER_C.SHIPPING_ORDER_ID
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSHIPPING_ORDER_ID(String SHIPPING_ORDER_ID) {
        this.SHIPPING_ORDER_ID = SHIPPING_ORDER_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.ORDER_TYPE
     *
     * @return the value of SHIPPING_ORDER_C.ORDER_TYPE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getORDER_TYPE() {
        return ORDER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.ORDER_TYPE
     *
     * @param ORDER_TYPE the value for SHIPPING_ORDER_C.ORDER_TYPE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setORDER_TYPE(String ORDER_TYPE) {
        this.ORDER_TYPE = ORDER_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.SHIPPER
     *
     * @return the value of SHIPPING_ORDER_C.SHIPPER
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getSHIPPER() {
        return SHIPPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.SHIPPER
     *
     * @param SHIPPER the value for SHIPPING_ORDER_C.SHIPPER
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSHIPPER(String SHIPPER) {
        this.SHIPPER = SHIPPER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CONSIGNEE
     *
     * @return the value of SHIPPING_ORDER_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCONSIGNEE() {
        return CONSIGNEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CONSIGNEE
     *
     * @param CONSIGNEE the value for SHIPPING_ORDER_C.CONSIGNEE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCONSIGNEE(String CONSIGNEE) {
        this.CONSIGNEE = CONSIGNEE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.NOTIFY_PARTY
     *
     * @return the value of SHIPPING_ORDER_C.NOTIFY_PARTY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getNOTIFY_PARTY() {
        return NOTIFY_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.NOTIFY_PARTY
     *
     * @param NOTIFY_PARTY the value for SHIPPING_ORDER_C.NOTIFY_PARTY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setNOTIFY_PARTY(String NOTIFY_PARTY) {
        this.NOTIFY_PARTY = NOTIFY_PARTY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.LC_NO
     *
     * @return the value of SHIPPING_ORDER_C.LC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getLC_NO() {
        return LC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.LC_NO
     *
     * @param LC_NO the value for SHIPPING_ORDER_C.LC_NO
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLC_NO(String LC_NO) {
        this.LC_NO = LC_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.PORT_OF_LOADING
     *
     * @return the value of SHIPPING_ORDER_C.PORT_OF_LOADING
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getPORT_OF_LOADING() {
        return PORT_OF_LOADING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.PORT_OF_LOADING
     *
     * @param PORT_OF_LOADING the value for SHIPPING_ORDER_C.PORT_OF_LOADING
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setPORT_OF_LOADING(String PORT_OF_LOADING) {
        this.PORT_OF_LOADING = PORT_OF_LOADING;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.PORT_OF_TRANS
     *
     * @return the value of SHIPPING_ORDER_C.PORT_OF_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getPORT_OF_TRANS() {
        return PORT_OF_TRANS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.PORT_OF_TRANS
     *
     * @param PORT_OF_TRANS the value for SHIPPING_ORDER_C.PORT_OF_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setPORT_OF_TRANS(String PORT_OF_TRANS) {
        this.PORT_OF_TRANS = PORT_OF_TRANS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.PORT_OF_DISCHARGE
     *
     * @return the value of SHIPPING_ORDER_C.PORT_OF_DISCHARGE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getPORT_OF_DISCHARGE() {
        return PORT_OF_DISCHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.PORT_OF_DISCHARGE
     *
     * @param PORT_OF_DISCHARGE the value for SHIPPING_ORDER_C.PORT_OF_DISCHARGE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setPORT_OF_DISCHARGE(String PORT_OF_DISCHARGE) {
        this.PORT_OF_DISCHARGE = PORT_OF_DISCHARGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.LOADING_DATE
     *
     * @return the value of SHIPPING_ORDER_C.LOADING_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getLOADING_DATE() {
        return LOADING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.LOADING_DATE
     *
     * @param LOADING_DATE the value for SHIPPING_ORDER_C.LOADING_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLOADING_DATE(Date LOADING_DATE) {
        this.LOADING_DATE = LOADING_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.LIMIT_DATE
     *
     * @return the value of SHIPPING_ORDER_C.LIMIT_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getLIMIT_DATE() {
        return LIMIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.LIMIT_DATE
     *
     * @param LIMIT_DATE the value for SHIPPING_ORDER_C.LIMIT_DATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setLIMIT_DATE(Date LIMIT_DATE) {
        this.LIMIT_DATE = LIMIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.IS_BATCH
     *
     * @return the value of SHIPPING_ORDER_C.IS_BATCH
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getIS_BATCH() {
        return IS_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.IS_BATCH
     *
     * @param IS_BATCH the value for SHIPPING_ORDER_C.IS_BATCH
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setIS_BATCH(String IS_BATCH) {
        this.IS_BATCH = IS_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.IS_TRANS
     *
     * @return the value of SHIPPING_ORDER_C.IS_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getIS_TRANS() {
        return IS_TRANS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.IS_TRANS
     *
     * @param IS_TRANS the value for SHIPPING_ORDER_C.IS_TRANS
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setIS_TRANS(String IS_TRANS) {
        this.IS_TRANS = IS_TRANS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.COPY_NUM
     *
     * @return the value of SHIPPING_ORDER_C.COPY_NUM
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCOPY_NUM() {
        return COPY_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.COPY_NUM
     *
     * @param COPY_NUM the value for SHIPPING_ORDER_C.COPY_NUM
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCOPY_NUM(String COPY_NUM) {
        this.COPY_NUM = COPY_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CNOTE
     *
     * @return the value of SHIPPING_ORDER_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCNOTE() {
        return CNOTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CNOTE
     *
     * @param CNOTE the value for SHIPPING_ORDER_C.CNOTE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCNOTE(String CNOTE) {
        this.CNOTE = CNOTE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.SPECIAL_CONDITION
     *
     * @return the value of SHIPPING_ORDER_C.SPECIAL_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getSPECIAL_CONDITION() {
        return SPECIAL_CONDITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.SPECIAL_CONDITION
     *
     * @param SPECIAL_CONDITION the value for SHIPPING_ORDER_C.SPECIAL_CONDITION
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSPECIAL_CONDITION(String SPECIAL_CONDITION) {
        this.SPECIAL_CONDITION = SPECIAL_CONDITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.FREIGHT
     *
     * @return the value of SHIPPING_ORDER_C.FREIGHT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getFREIGHT() {
        return FREIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.FREIGHT
     *
     * @param FREIGHT the value for SHIPPING_ORDER_C.FREIGHT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setFREIGHT(String FREIGHT) {
        this.FREIGHT = FREIGHT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CHECK_BY
     *
     * @return the value of SHIPPING_ORDER_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCHECK_BY() {
        return CHECK_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CHECK_BY
     *
     * @param CHECK_BY the value for SHIPPING_ORDER_C.CHECK_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCHECK_BY(String CHECK_BY) {
        this.CHECK_BY = CHECK_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.STATE
     *
     * @return the value of SHIPPING_ORDER_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Short getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.STATE
     *
     * @param STATE the value for SHIPPING_ORDER_C.STATE
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setSTATE(Short STATE) {
        this.STATE = STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CREATE_BY
     *
     * @return the value of SHIPPING_ORDER_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_BY() {
        return CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CREATE_BY
     *
     * @param CREATE_BY the value for SHIPPING_ORDER_C.CREATE_BY
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_BY(String CREATE_BY) {
        this.CREATE_BY = CREATE_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CREATE_DEPT
     *
     * @return the value of SHIPPING_ORDER_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public String getCREATE_DEPT() {
        return CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CREATE_DEPT
     *
     * @param CREATE_DEPT the value for SHIPPING_ORDER_C.CREATE_DEPT
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_DEPT(String CREATE_DEPT) {
        this.CREATE_DEPT = CREATE_DEPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SHIPPING_ORDER_C.CREATE_TIME
     *
     * @return the value of SHIPPING_ORDER_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public Date getCREATE_TIME() {
        return CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SHIPPING_ORDER_C.CREATE_TIME
     *
     * @param CREATE_TIME the value for SHIPPING_ORDER_C.CREATE_TIME
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    public void setCREATE_TIME(Date CREATE_TIME) {
        this.CREATE_TIME = CREATE_TIME;
    }
}