package com.lanou.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.AuthUser;
@MapperScan
public interface AuthUserMapper {

	/**
	 * 登录方法
	 * @param username 用户名	
	 * @param password 密码
	 * @return
	 */
	AuthUser selectByUserAndPwd(@Param(value = "username") String username, @Param(value="password") String password);
	/**
	 * 根据用户名查询用户
	 * @param username
	 * @return
	 */
	List<AuthUser> selectByUser(@Param(value = "username") String username);
	/**
	 * 根据id查询用户信息
	 * @param AUTH_USER_ID
	 * @return
	 */
    int deleteByPrimaryKey(String AUTH_USER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    AuthUser selectByPrimaryKey(String AUTH_USER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTH_USER_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKey(AuthUser record);
}