package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.entity.Extcproductc;
import com.lanou.entity.Extcproducthisc;
@MapperScan
public interface ExtcproducthiscMapper {
	
	/**
	 * 根据合同货物查询附件
	 * @return
	 */
	List<Extcproducthisc> selectByList(String id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int deleteByPrimaryKey(String EXT_CPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int insert(Extcproducthisc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int insertSelective(Extcproductc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    Extcproducthisc selectByPrimaryKey(String EXT_CPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int updateByPrimaryKeySelective(Extcproducthisc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_CPRODUCT_HIS_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int updateByPrimaryKey(Extcproducthisc record);
}