package com.lanou.mapper;

import com.lanou.entity.Exteproductc;

public interface ExteproductcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int deleteByPrimaryKey(String EXT_EPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int insert(Exteproductc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int insertSelective(Exteproductc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    Exteproductc selectByPrimaryKey(String EXT_EPRODUCT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int updateByPrimaryKeySelective(Exteproductc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EXT_EPRODUCT_C
     *
     * @mbg.generated Fri Jan 05 15:47:01 CST 2018
     */
    int updateByPrimaryKey(Exteproductc record);
}