package com.lanou.mapper;

import java.util.List;

import org.mybatis.spring.annotation.MapperScan;

import com.lanou.bean.FactoryRecordBean;
import com.lanou.entity.LoginLogp;
@MapperScan
public interface LoginLogpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int deleteByPrimaryKey(String LOGIN_LOG_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insert(LoginLogp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insertSelective(LoginLogp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    LoginLogp selectByPrimaryKey(String LOGIN_LOG_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKeySelective(LoginLogp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGIN_LOG_P
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKey(LoginLogp record);
    
    List<FactoryRecordBean> selectByTime();
    
    List<FactoryRecordBean> selectByYear(String year);
}