package com.lanou.mapper;

import com.lanou.entity.ShippinGorder;

public interface ShippinGorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int deleteByPrimaryKey(String SHIPPING_ORDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insert(ShippinGorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int insertSelective(ShippinGorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    ShippinGorder selectByPrimaryKey(String SHIPPING_ORDER_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKeySelective(ShippinGorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SHIPPING_ORDER_C
     *
     * @mbg.generated Mon Jan 08 14:19:28 CST 2018
     */
    int updateByPrimaryKey(ShippinGorder record);
}